# Generated by Django 2.1.4 on 2019-01-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_auto_20190102_1250'),
        ('accounts', '0002_auto_20190102_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='empresa',
        ),
        migrations.AddField(
            model_name='profile',
            name='empresa',
            field=models.ManyToManyField(blank=True, null=True, to='empresas.Empresa'),
        ),
    ]
