# Generated by Django 2.1.4 on 2019-01-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_auto_20190102_1259'),
        ('accounts', '0003_auto_20190102_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='empresa',
        ),
        migrations.AddField(
            model_name='profile',
            name='empresas',
            field=models.ManyToManyField(to='empresas.Empresa'),
        ),
    ]
