# Generated by Django 2.1.4 on 2019-01-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=140)),
                ('lote', models.IntegerField(unique=True)),
                ('etapa', models.IntegerField()),
                ('razao_social', models.CharField(blank=True, default=None, max_length=140)),
                ('logo', models.ImageField(blank=True, default=None, null=True, upload_to='concessionarias/img/empresas/logo/')),
                ('grupo', models.CharField(blank=True, default=None, max_length=140)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True)),
                ('sede', models.CharField(blank=True, default=None, max_length=140)),
                ('rodovias', models.TextField(blank=True, default=None, max_length=360)),
            ],
        ),
    ]
