# Generated by Django 2.1.4 on 2019-01-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='empresas/logo/'),
        ),
    ]
