# Generated by Django 2.1.4 on 2019-01-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_auto_20190102_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='etapa',
            field=models.IntegerField(null=True, verbose_name='etapa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='lote',
            field=models.IntegerField(null=True, unique=True, verbose_name='lote'),
        ),
    ]
